#!/usr/bin/env node

"use strict";

var http = require('http');
var httpProxy = require('./network_simulation/lib/proxy');
var checkServer = require('./network_simulation/lib/check_server');
var nopt = require('nopt');
var url = require('url');

var RequestData = function (request, response, buffer) {
  this.request = request;
  this.response = response;
  this.buffer = buffer;
};

function ipFromRequest(reqData) {
  return reqData.request.headers['x-forwarded-for'];
}

function rejectRequest(reqData) {
  reqData.response.writeHead(400);
  reqData.response.end();
}

var ip_pool={};
var ip_time={};
var total_reqs=0;
var unique_reqs=0;
var active_requests=0;
var start_time = Date.now();
var MAX_RATE = 250; // with two backends

function currently_blacklisted(ip)
{
  var rate = 0;
  var now = Date.now();

  total_reqs++;
  if (ip in ip_pool) {
    ip_pool[ip]++;
    if (now == ip_time[ip]) rate = 1000000;
    else rate = 1000 / (now - ip_time[ip]);
    ip_time[ip] = now;
  } else {
    unique_reqs++;
    ip_pool[ip] = 1;
    ip_time[ip] = Date.now();
  }

  var avg_reqs = 1.0 * total_reqs/unique_reqs;
  var avg_rate = 1000 * total_reqs / (now - start_time);

  // first time ip
  if (rate == 0) return false;

  if (ip_pool[ip] > avg_reqs) return true;
  if (rate > avg_rate || rate > MAX_RATE) return true;
  return false;
}

var Queue = function (proxies, parameters) {
  this.proxies = proxies;
  this.parameters = parameters;
  this.current = -1;
  this.totalproxies = proxies.length;
};
Queue.prototype.takeRequest = function (reqData) {
  var ip = ipFromRequest(reqData);
  if (currently_blacklisted(ip)) {
     if (active_requests > this.totalproxies) {
        return rejectRequest(reqData);
     }
  }
  this.current = (this.current+1) % this.totalproxies;
  active_requests++;
  this.proxies[this.current].proxyRequest(reqData.request, reqData.response, reqData.buffer);
};
Queue.prototype.requestFinished = function () {
  active_requests--;
  return;
};

function checkBackends(targets, path, response) {
  var toCheck = targets.map(function (target) {
    var output = {};
    output['host'] = target['host'];
    output['port'] = target['port'];
    output['path'] = path;
    return output;
  });
  var success = function () {
    response.writeHead(200, {"Content-Type": "application/json"});
    response.end()
  };
  var error = function () {
    response.writeHead(500, {"Content-Type": "application/json"});
    response.end()
  };
  checkServer.checkServers(toCheck, success, error);
}

function main() {
  var opts = {
    "out-ports": String,
    "in-port": String,
  };
  var parsed = nopt(opts),
      inPort = parsed['in-port'] || '3000',
      outPorts = parsed['out-ports'] ? parsed['out-ports'].split(",") : ['3001'],
      targets = [],
      target,
      proxies = [],
      proxy,
      i;

  for (i = 0; i < outPorts.length; i++) {
    target = {'host': 'localhost', 'port': outPorts[i]};
    targets.push(target);
    proxy = new httpProxy.HttpProxy({'target': target});
    proxy.identifier = i;
    proxies.push(proxy);
  }

  var queue = new Queue(proxies, {});
  for (i = 0; i < proxies.length; i++) {
    proxy = proxies[i];
    proxy.on("end", queue.requestFinished);
  }

  var server = http.createServer(function (req, res) {
    if (req.method === "HEAD") {
      // HEAD requests are used to monitor the status of the simulation
      // proxies[0].proxyRequest(reqData.request, reqData.response, reqData.buffer);
      checkBackends(targets, url.parse(req.url)['pathname'], res);
    } else {
      var buffer = httpProxy.buffer(req);
      var reqData = new RequestData(req, res, buffer);
      queue.takeRequest(reqData);
    }
  });

  server.on('close', function () {
    for (i = 0; i < proxies.length; i++) {
      proxies[i].close();
    }
  });
  console.log("The shield is up and listening.");
  server.listen(inPort);
}

main();
