#!/bin/sh

if [ `expr match "$username" '^.*@itbhu[.]ac[.]in'` -eq 0 ]
then
  username="${username}@itbhu.ac.in"
fi

blacklisted=`cat /etc/openvpn/blacklist`
declare -A blacklist
for bluser in $blacklisted
do 
  blacklist[$bluser]=1
done

if [[ ${blacklist[$username]} ]]
then
  exit 1
fi

outp=$(curl  --silent  --location https://www.google.com/accounts/ClientLogin   --data "Email=$username&Passwd=$password"  --header 'Content-Type:application/x-www-form-urlencoded')
if [[ "$outp" =~ ^SID= ]]
then
exit 0
else
exit 1
fi
